// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_XEuNTin0zsW66kRHX75QB-Sx7ISTF3k',
    appId: '1:1032681753942:web:f3583ba5bf92c2e1badaf7',
    messagingSenderId: '1032681753942',
    projectId: 'fir-5955e',
    authDomain: 'fir-5955e.firebaseapp.com',
    storageBucket: 'fir-5955e.firebasestorage.app',
    measurementId: 'G-EVC1DK3RBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpnJkLlxOYC1F5SsJy3iyqo2RFpLfctA',
    appId: '1:1032681753942:android:a473ad74905433abbadaf7',
    messagingSenderId: '1032681753942',
    projectId: 'fir-5955e',
    storageBucket: 'fir-5955e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_XEuNTin0zsW66kRHX75QB-Sx7ISTF3k',
    appId: '1:1032681753942:web:851f60b8328b7737badaf7',
    messagingSenderId: '1032681753942',
    projectId: 'fir-5955e',
    authDomain: 'fir-5955e.firebaseapp.com',
    storageBucket: 'fir-5955e.firebasestorage.app',
    measurementId: 'G-NS3RZZ2WYL',
  );
}
